version: '3.8'

services:
  app:
    build: .
    container_name: rifa-luteranos-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_DB: rifa-luterano-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - luteranos_data:/var/lib/postgresql
volumes:
  luteranos_data: